spring:
  profiles:
     active:
     - dev
---
spring:
  profiles: dev
  application:
    name: microservice-config-jing-dev
---
spring:
  profiles: test
  application:
    name: microservice-config-jing-test